#  Copyright (C) 2018-2024 LEIDOS.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

services:
  roscore:
    image: ${DOCKER_ORG}/carma-base:${DOCKER_TAG}-noetic
    network_mode: host
    container_name: roscore
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.0.100
    volumes:
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/logs:/opt/carma/logs
    restart: always
    command: roscore

  platform:
    image: usdotfhwastolcandidate/carma-platform:vip-demo
    network_mode: host
    container_name: platform
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.0.100
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  pedestrian_publisher:
    image: usdotfhwastoldev/carma-platform:develop-ped-publisher
    network_mode: host
    container_name: pedestrian_publisher
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
      - /home/carma/carma_ws/src/carma-developer-tools/pedestrian_publisher/config/pedestrian_params.yaml:/home/carma/workspace/install/pedestrian_publisher/share/pedestrian_publisher/config/pedestrian_params.yaml
      - /home/carma/carma_ws/src/carma-developer-tools/pedestrian_publisher/launch/pedestrian_publisher_launch.py:/home/carma/workspace/install/pedestrian_publisher/share/pedestrian_publisher/launch/pedestrian_publisher_launch.py
      - /home/carma/carma_ws/src/carma-developer-tools/pedestrian_publisher/pedestrian_publisher/pedestrian_publisher.py:/home/carma/workspace/install/pedestrian_publisher/lib/python3.10/site-packages/pedestrian_publisher/pedestrian_publisher.py
    command: bash -c 'source /opt/carma/install/setup.bash && 
      source /home/carma/workspace/install/setup.bash &&
      ros2 launch pedestrian_publisher pedestrian_publisher_launch.py'

  ros1_bridge:
    image: ${DOCKER_ORG}/carma-msgs:${DOCKER_TAG}
    network_mode: host
    container_name: ros1_bridge
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.0.100
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
    command: bash -c 'wait-for-it localhost:11311 -- rosparam load /opt/carma/vehicle/config/bridge.yml && source /home/carma/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  lightbar-driver:
    image: ${DOCKER_ORG}/carma-lightbar-driver:${DOCKER_TAG}
    network_mode: host
    container_name: lightbar-driver
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    environment:
      - ROS_IP=192.168.0.100
    command: bash -c 'export ROS_NAMESPACE=$${CARMA_INTR_NS} && wait-for-it localhost:11311 -- ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=lightbar_driver'

  v2x_ros_driver:
    image: usdotfhwastol/carma-cohda-dsrc-driver:carma-system-4.5.0
    container_name: v2x-ros-driver
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
        #- /home/carma/carma_ws/src/v2x-ros-driver/v2x_ros_driver/config/wave.json:/opt/carma/install/dsrc_driver/share/dsrc_driver/config/wave.json
        #- /home/carma/carma_ws/src/v2x-ros-driver/v2x_ros_driver/etc/wave.json:/opt/carma/install/dsrc_driver/share/dsrc_driver/etc/wave.json
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=v2x_ros_driver'

  ssc_controller_driver:
    image: ${DOCKER_ORG}/carma-ssc-interface-wrapper:${DOCKER_TAG}-humble
    container_name: ssc_controller_driver
    network_mode: host
    privileged: true # Grant access to kvaser
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.0.100
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=ssc_interface_wrapper_ros2'

  novatel_gnss_imu_driver:
    image: ${DOCKER_ORG}/carma-novatel-oem7-driver-wrapper:${DOCKER_TAG}
    container_name: carma-novatel-oem7-driver-wrapper
    network_mode: host
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
    command: bash -c 'source /opt/carma/install/setup.bash && ros2 launch /opt/carma/vehicle/config/drivers.launch.py drivers:=carma_novatel_driver_wrapper'
